# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cd281621eee5d37aaa948a311a7008f6e2acb1fc383fcfdf5607822bddac5fd6b474c4dc0ca4790d1ca67f6c1af7a2e8e98d503d51d6aa9a7aaf853d8d0d2d4b

test:
  secret_key_base: b38e460f3723b021db944acf29f3893d904956a0254dce63bda51fbd2552c881e7c81e15b31f7e519f796f2d1185048b119cdab9dcc0774d5fc5d48dc1484c51

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
